### ISSUE TITLE
Fix type checking in TS pre 5.4

### ISSUE THREAD

**Issue by diogob** [seasonedcc/development-of-composable-functions#1]

**Comment by diogob** [comment]
I have tried different Deno versions using [dvm](https://github.com/justjavac/dvm).
 
* 1.36.1 (TS 5.1.6)
* 1.37.2 (TS 5.2.2)
* 1.41.3 (TS 5.3.3)

All work fine. @gustavoguichard is this still failing on your side? Otherwise we can probably close this one

**Comment by gustavoguichard** [comment]
This is unrelated to TS version but a problem with circular dependencies and module resolution so I'll close it for now as I expect us to solve it whenever we regroup the modules.
